spring.application.name=eventhub-backend
jwt.secret=8f4a2e91c6d73b5f0a9e2c4d6f8b1a3e5c7d9f2b4a6e8c0d2f4b6a8e0c2d4f6a
spring.profiles.active=local
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB



