spring.application.name=eventhub-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/eventhub
spring.datasource.username=postgres
spring.datasource.password=sambatra

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

